# Generated by Django 6.0.4 on 2026-04-23 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField(default=0)),
                ("categoria", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.DeleteModel(
            name="Endereço",
        ),
        migrations.DeleteModel(
            name="FormaPagamento",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ItemPedido",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.AlterModelOptions(
            name="vendedor",
            options={"ordering": ["nome"]},
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="endereco",
        ),
        migrations.AddField(
            model_name="vendedor",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="avaliacao",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="cpf_cnpj",
            field=models.CharField(
                default="XXX.XXX.XXX -XX", max_length=18, unique=True
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendedor",
            name="email",
            field=models.EmailField(
                default="sem-email@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="vendedor",
            table="vendedores",
        ),
    ]
