# Generated by Django 6.0.4 on 2026-04-28 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_produto_delete_endereço_delete_formapagamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilVendedor",
            fields=[
                (
                    "vendedor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil",
                        serialize=False,
                        to="backend.vendedor",
                    ),
                ),
                ("razao_social", models.CharField(blank=True, max_length=150)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=20)),
                ("banco", models.CharField(blank=True, max_length=50)),
                ("agencia", models.CharField(blank=True, max_length=10)),
                ("conta", models.CharField(blank=True, max_length=20)),
                ("chave_pix", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vendedor",
            options={},
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nome",
        ),
        migrations.AddField(
            model_name="produto",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="produto",
            table=None,
        ),
        migrations.AlterModelTable(
            name="vendedor",
            table=None,
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="backend.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço congelado no momento da compra",
                        max_digits=10,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_vendidos",
                        to="backend.produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="backend.pedido",
                    ),
                ),
            ],
        ),
    ]
